### ISSUE TITLE
Error while starting.

### ISSUE THREAD

**Issue by mjour** [bcgov/aries-vcr-issuer-controller#76]
Now I am starting with `./manage start` in the directory of docker.
But I got the errors.
![image](https://user-images.githubusercontent.com/96822355/221082630-89c5cb30-042f-4458-b7f4-a8712881411d.png)

**Comment by WadeBarnes** [comment]
It looks like you did not do a `./manage build` first and it's running parts of the build when you run `./manage start`.  That's just an observation.  The errors look like they are due to issues downloading and installing the necessary packages.  Are you running this behind a corporate firewall or proxy?

The build, `./manage build` worked for me when I pulled the latest version of the code.  I have not attempted to run a full app set with Aries-VCR and von-network though.

You need to get past the build errors first.

**Comment by ianco** [comment]
Make sure you follow all the tutorial steps:  https://github.com/bcgov/aries-vcr-issuer-controller/blob/main/GettingStartedTutorial.md

Note the `. init.sh` people often miss that one

**Comment by mjour** [comment]
I run . init.sh.
But the result is same.

**Comment by kthomas-digicat** [comment]
Hi @WadeBarnes I followed the instructions and I still find the application exiting with error. It starts with a column name 'p.proisagg' not found in the DB ('Schema Spy').
`vcr-schema-spy-1  |   ____       _                          ____
vcr-schema-spy-1  |  / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
vcr-schema-spy-1  |  \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
vcr-schema-spy-1  |   ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
vcr-schema-spy-1  |  |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
vcr-schema-spy-1  |                                              |_|    |___/
vcr-schema-spy-1  | 
vcr-schema-spy-1  |                                               6.1.0
vcr-schema-spy-1  | 
vcr-schema-spy-1  | SchemaSpy generates an HTML representation of a database schema's relationships.
vcr-schema-spy-1  | SchemaSpy comes with ABSOLUTELY NO WARRANTY.
vcr-schema-spy-1  | SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
vcr-schema-spy-1  | http://www.gnu.org/licenses/
vcr-schema-spy-1  | 
vcr-schema-spy-1  | INFO  - Starting Main v6.1.0 on 92670e68eb34 with PID 10 (/app/lib/schemaspy.jar started by ? in /app)
vcr-schema-spy-1  | INFO  - The following profiles are active: default
vcr-schema-spy-1  | INFO  - Started Main in 1.131 seconds (JVM running for 1.7)
vcr-schema-spy-1  | INFO  - Starting schema analysis
vcr-schema-spy-1  | INFO  - Connected to PostgreSQL - 14.7 (Debian 14.7-1.pgdg110+1)
vcr-schema-spy-1  | INFO  - Gathering schema details
vcr-vcr-db-1      | 2023-05-22 12:45:15.870 UTC [78] ERROR:  column p.proisagg does not exist at character 34
vcr-vcr-db-1      | 2023-05-22 12:45:15.870 UTC [78] HINT:  Perhaps you meant to reference the column "p.prolang".
vcr-vcr-db-1      | 2023-05-22 12:45:15.870 UTC [78] STATEMENT:  select r.routine_name, case when p.proisagg then 'AGGREGATE' else 'FUNCTION' end as routine_type, case when p.proretset then 'SETOF ' else '' end || case when r.data_type = 'USER-DEFINED' then r.type_udt_name else r.data_type end as dtd_identifier, r.external_language as routine_body, r.routine_definition, r.sql_data_access, r.security_type, r.is_deterministic, d.description as routine_comment from information_schema.routines r left join pg_namespace ns on r.routine_schema = ns.nspname left join pg_proc p on ns.oid = p.pronamespace and r.routine_name = p.proname left join pg_description d on d.objoid = p.oid where r.routine_schema = $1
vcr-schema-spy-1  | Gathering schema details.............................WARN  - Failed to retrieve stored procedure/function details using sql 'select r.routine_name, case when p.proisagg then 'AGGREGATE' else 'FUNCTION' end as routine_type, case when p.proretset then 'SETOF ' else '' end || case when r.data_type = 'USER-DEFINED' then r.type_udt_name else r.data_type end as dtd_identifier, r.external_language as routine_body, r.routine_definition, r.sql_data_access, r.security_type, r.is_deterministic, d.description as routine_comment from information_schema.routines r left join pg_namespace ns on r.routine_schema = ns.nspname left join pg_proc p on ns.oid = p.pronamespace and r.routine_name = p.proname left join pg_description d on d.objoid = p.oid where r.routine_schema = :schema'
vcr-schema-spy-1  | ERROR: column p.proisagg does not exist
vcr-schema-spy-1  |   Hint: Perhaps you meant to reference the column "p.prolang".
vcr-schema-spy-1  |   Position: 34
vcr-schema-spy-1  | (0sec)
vcr-schema-spy-1  | Connecting relationships.............................(0sec)
vcr-schema-spy-1  | Writing/graphing summary.INFO  - Gathered schema details in 0 seconds
vcr-schema-spy-1  | INFO  - Writing/graphing summary
vcr-schema-spy-1  | INFO  - Graphviz rendered set to ''
vcr-schema-spy-1  | ........(1sec)
vcr-schema-spy-1  | Writing/diagramming detailsINFO  - Completed summary in 1 seconds
vcr-schema-spy-1  | INFO  - Writing/diagramming details
vcr-schema-spy-1  | ..........................(3sec)
vcr-schema-spy-1  | Wrote relationship details of 26 tables/views to directory '/var/www/html' in 5 seconds.
vcr-schema-spy-1  | View the results by opening /var/www/html/index.html
vcr-schema-spy-1  | INFO  - Wrote table details in 3 seconds
vcr-schema-spy-1  | INFO  - Wrote relationship details of 26 tables/views to directory '/var/www/html' in 5 seconds.
vcr-schema-spy-1  | INFO  - View the results by opening /var/www/html/index.html
vcr-schema-spy-1  | INFO  - StackTraces have been omitted, use `-debug` when executing SchemaSpy to see them
vcr-schema-spy-1  | Starting webserver on port 8080 ...
vcr-schema-spy-1  | {"level":"info","ts":1684759521.2988563,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
vcr-schema-spy-1  | {"level":"info","ts":1684759521.3042605,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["localhost:2019","[::1]:2019","127.0.0.1:2019"]}
vcr-schema-spy-1  | {"level":"info","ts":1684759521.3054557,"logger":"tls","msg":"cleaned up storage units"}
vcr-schema-spy-1  | {"level":"error","ts":1684759521.3055892,"msg":"unable to create folder for config autosave","dir":"/.config/caddy","error":"mkdir /.config: permission denied"}
vcr-schema-spy-1  | {"level":"info","ts":1684759521.305601,"msg":"serving initial configuration"}
vcr-schema-spy-1  | {"level":"info","ts":1684759521.3056815,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc00031a000"}
vcr-vcr-agent-1   | Traceback (most recent call last):
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 174, in open
vcr-vcr-agent-1   |     self.handle = await indy.pool.open_pool_ledger(self.name, pool_config)
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/pool.py", line 88, in open_pool_ledger
vcr-vcr-agent-1   |     open_pool_ledger.cb)
vcr-vcr-agent-1   | indy.error.PoolLedgerTimeout
vcr-vcr-agent-1   | 
vcr-vcr-agent-1   | The above exception was the direct cause of the following exception:
vcr-vcr-agent-1   | 
vcr-vcr-agent-1   | Traceback (most recent call last):
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/provision.py", line 38, in provision
vcr-vcr-agent-1   |     if await ledger_config(root_profile, public_did and public_did.did, True):
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/config/ledger.py", line 71, in ledger_config
vcr-vcr-agent-1   |     async with ledger:
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 276, in __aenter__
vcr-vcr-agent-1   |     await self.pool.context_open()
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 209, in context_open
vcr-vcr-agent-1   |     await self.open()
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 174, in open
vcr-vcr-agent-1   |     self.handle = await indy.pool.open_pool_ledger(self.name, pool_config)
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/indy/sdk/error.py", line 27, in __exit__
vcr-vcr-agent-1   |     ) from err_value
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 174, in open
vcr-vcr-agent-1   |     self.handle = await indy.pool.open_pool_ledger(self.name, pool_config)
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/pool.py", line 88, in open_pool_ledger
vcr-vcr-agent-1   |     open_pool_ledger.cb)
vcr-vcr-agent-1   | aries_cloudagent.ledger.error.LedgerConfigError: Exception opening pool ledger default: Error: Pool timeout
vcr-vcr-agent-1   |   Caused by: Pool timeout
vcr-vcr-agent-1   | 
vcr-vcr-agent-1   | 
vcr-vcr-agent-1   | The above exception was the direct cause of the following exception:
vcr-vcr-agent-1   | 
vcr-vcr-agent-1   | Traceback (most recent call last):
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/runpy.py", line 193, in _run_module_as_main
vcr-vcr-agent-1   |     "__main__", mod_spec)
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/runpy.py", line 85, in _run_code
vcr-vcr-agent-1   |     exec(code, run_globals)
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/__main__.py", line 74, in <module>
vcr-vcr-agent-1   |     main(sys.argv)
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/__main__.py", line 71, in main
vcr-vcr-agent-1   |     run(args)
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/__main__.py", line 64, in run
vcr-vcr-agent-1   |     run_command(command, args)
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/__init__.py", line 37, in run_command
vcr-vcr-agent-1   |     module.execute(argv)
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/provision.py", line 62, in execute
vcr-vcr-agent-1   |     loop.run_until_complete(provision(settings))
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
vcr-vcr-agent-1   |     return future.result()
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/provision.py", line 45, in provision
vcr-vcr-agent-1   |     raise ProvisionError("Error during provisioning") from e
vcr-vcr-agent-1   | aries_cloudagent.commands.provision.ProvisionError: Error during provisioning
vcr-vcr-agent-1   | 
vcr-vcr-agent-1   | Shutting down
vcr-vcr-agent-1   | 2023-05-22 12:46:46,146 aries_cloudagent.commands.start ERROR Exception during startup:
vcr-vcr-agent-1   | Traceback (most recent call last):
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 174, in open
vcr-vcr-agent-1   |     self.handle = await indy.pool.open_pool_ledger(self.name, pool_config)
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/pool.py", line 88, in open_pool_ledger
vcr-vcr-agent-1   |     open_pool_ledger.cb)
vcr-vcr-agent-1   | indy.error.PoolLedgerTimeout
vcr-vcr-agent-1   | 
vcr-vcr-agent-1   | The above exception was the direct cause of the following exception:
vcr-vcr-agent-1   | 
vcr-vcr-agent-1   | Traceback (most recent call last):
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 72, in init
vcr-vcr-agent-1   |     await startup
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 28, in start_app
vcr-vcr-agent-1   |     await conductor.setup()
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/core/conductor.py", line 101, in setup
vcr-vcr-agent-1   |     self.root_profile, self.setup_public_did and self.setup_public_did.did
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/config/ledger.py", line 71, in ledger_config
vcr-vcr-agent-1   |     async with ledger:
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 276, in __aenter__
vcr-vcr-agent-1   |     await self.pool.context_open()
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 209, in context_open
vcr-vcr-agent-1   |     await self.open()
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 174, in open
vcr-vcr-agent-1   |     self.handle = await indy.pool.open_pool_ledger(self.name, pool_config)
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/indy/sdk/error.py", line 27, in __exit__
vcr-vcr-agent-1   |     ) from err_value
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 174, in open
vcr-vcr-agent-1   |     self.handle = await indy.pool.open_pool_ledger(self.name, pool_config)
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/pool.py", line 88, in open_pool_ledger
vcr-vcr-agent-1   |     open_pool_ledger.cb)
vcr-vcr-agent-1   | aries_cloudagent.ledger.error.LedgerConfigError: Exception opening pool ledger default: Error: Pool timeout
vcr-vcr-agent-1   |   Caused by: Pool timeout
vcr-vcr-agent-1   | 
vcr-vcr-agent-1 exited with code 0`

**Comment by kthomas-digicat** [comment]
Hi @WadeBarnes I followed the instructions and I still find the application exiting with error. It starts with a column name 'p.proisagg' not found in the DB ('Schema Spy').

![image](https://github.com/bcgov/aries-vcr-issuer-controller/assets/64412956/9815fcea-2321-4173-be58-b4997f0a47f7)
![image](https://github.com/bcgov/aries-vcr-issuer-controller/assets/64412956/f2f4ca2d-6494-4b03-af63-5f145274b624)
