### ISSUE TITLE
5001 port get 502 502 Bad Gateway

### ISSUE THREAD

**Issue by mjour** [bcgov/aries-vcr-issuer-controller#79]
Here is error log.
```
myorg-myorg-wallet-db-1    | syncing data to disk ... ok
myorg-myorg-wallet-db-1    |
myorg-myorg-wallet-db-1    | Success. You can now start the database server using:
myorg-myorg-wallet-db-1    |
myorg-myorg-wallet-db-1    |     pg_ctl -D /var/lib/pgsql/data/userdata -l logfile start
myorg-myorg-wallet-db-1    |
myorg-myorg-wallet-db-1    | waiting for server to start....LOG:  redirecting log output to logging collector process
myorg-myorg-wallet-db-1    | HINT:  Future log output will appear in directory "pg_log".
myorg-myorg-wallet-db-1    | . done
myorg-myorg-wallet-db-1    | server started
myorg-myorg-wallet-db-1    | /var/run/postgresql:5432 - accepting connections
myorg-myorg-wallet-db-1    | => sourcing /usr/share/container-scripts/postgresql/start/set_passwords.sh ...
myorg-myorg-wallet-db-1    | ALTER ROLE
myorg-myorg-wallet-db-1    | ALTER ROLE
myorg-myorg-wallet-db-1    | waiting for server to shut down.... done
myorg-myorg-wallet-db-1    | server stopped
myorg-myorg-wallet-db-1    | Starting server...
myorg-myorg-wallet-db-1    | LOG:  redirecting log output to logging collector process
myorg-myorg-wallet-db-1    | HINT:  Future log output will appear in directory "pg_log".
myorg-myorg-controller-1   | sleeping ...
myorg-myorg-controller-1   | Starting server ...
myorg-myorg-controller-1   | [2023-03-04 01:41:19 +0000] [1] [INFO] Starting gunicorn 20.1.0
myorg-myorg-controller-1   | [2023-03-04 01:41:19 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
myorg-myorg-controller-1   | [2023-03-04 01:41:19 +0000] [1] [INFO] Using worker: gevent
myorg-myorg-controller-1   | [2023-03-04 01:41:19 +0000] [8] [INFO] Booting worker with pid: 8
myorg-myorg-controller-1   | Configuration variable not defined: APPLICATION_URL
myorg-myorg-controller-1   | Configuration variable not defined: ENDPOINT_URL
myorg-myorg-controller-1   | Configuration variable not defined: ENDPOINT_URL
myorg-myorg-controller-1   | Configuration variable not defined: ENDPOINT_URL
myorg-myorg-controller-1   | Configuration variable not defined: ENDPOINT_URL
myorg-myorg-controller-1   | Exception in thread Thread-1:
myorg-myorg-controller-1   | Traceback (most recent call last):
myorg-myorg-controller-1   |   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
myorg-myorg-controller-1   |     conn = connection.create_connection(
myorg-myorg-controller-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
myorg-myorg-controller-1   |   File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
myorg-myorg-controller-1   |     raise err
myorg-myorg-controller-1   |   File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
myorg-myorg-controller-1   |     sock.connect(sa)
myorg-myorg-controller-1   |   File "/usr/local/lib/python3.11/site-packages/gevent/_socketcommon.py", line 607, in connect
myorg-myorg-controller-1   |     raise _SocketError(err, strerror(err))
myorg-myorg-controller-1   | ConnectionRefusedError: [Errno 111] Connection refused
myorg-myorg-controller-1   |
myorg-myorg-controller-1   | During handling of the above exception, another exception occurred:
myorg-myorg-controller-1   |
myorg-myorg-controller-1   | Traceback (most recent call last):
myorg-myorg-controller-1   |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
myorg-myorg-controller-1   |     httplib_response = self._make_request(
myorg-myorg-controller-1   |                        ^^^^^^^^^^^^^^^^^^^
myorg-myorg-controller-1   |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 398, in _make_request
myorg-myorg-controller-1   |     conn.request(method, url, **httplib_request_kw)
myorg-myorg-controller-1   |   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 239, in request
myorg-myorg-controller-1   |     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
myorg-myorg-controller-1   |   File "/usr/local/lib/python3.11/http/client.py", line 1282, in request
myorg-myorg-controller-1   |     self._send_request(method, url, body, headers, encode_chunked)
myorg-myorg-controller-1   |   File "/usr/local/lib/python3.11/http/client.py", line 1328, in _send_request
myorg-myorg-controller-1   |     self.endheaders(body, encode_chunked=encode_chunked)
myorg-myorg-controller-1   |   File "/usr/local/lib/python3.11/http/client.py", line 1277, in endheaders
myorg-myorg-controller-1   |     self._send_output(message_body, encode_chunked=encode_chunked)
myorg-myorg-controller-1   |   File "/usr/local/lib/python3.11/http/client.py", line 1037, in _send_output
myorg-myorg-controller-1   |     self.send(msg)
myorg-myorg-controller-1   |   File "/usr/local/lib/python3.11/http/client.py", line 975, in send
myorg-myorg-controller-1   |     self.connect()
myorg-myorg-controller-1   |   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 205, in connect
myorg-myorg-controller-1   |     conn = self._new_conn()
myorg-myorg-controller-1   |            ^^^^^^^^^^^^^^^^
myorg-myorg-controller-1   |   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
myorg-myorg-controller-1   |     raise NewConnectionError(
myorg-myorg-controller-1   | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f735241b490>: Failed to establish a new connection: [Errno 111] Connection refused
myorg-myorg-controller-1   |
myorg-myorg-controller-1   | During handling of the above exception, another exception occurred:
myorg-myorg-controller-1   |
myorg-myorg-controller-1   | Traceback (most recent call last):
myorg-myorg-controller-1   |   File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
myorg-myorg-controller-1   |     resp = conn.urlopen(
myorg-myorg-controller-1   |            ^^^^^^^^^^^^^
myorg-myorg-controller-1   |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
myorg-myorg-controller-1   |     retries = retries.increment(
myorg-myorg-controller-1   |               ^^^^^^^^^^^^^^^^^^
myorg-myorg-controller-1   |   File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
myorg-myorg-controller-1   |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
myorg-myorg-controller-1   | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='myorg-agent', port=8034): Max retries exceeded with url: /wallet/did/public (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f735241b490>: Failed to establish a new connection: [Errno 111] Connection refused'))
myorg-myorg-controller-1   |
myorg-myorg-controller-1   | During handling of the above exception, another exception occurred:
myorg-myorg-controller-1   |
myorg-myorg-controller-1   | Traceback (most recent call last):
myorg-myorg-controller-1   |   File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
myorg-myorg-controller-1   |     self.run()
myorg-myorg-controller-1   |   File "/app/controller/src/issuer.py", line 222, in run
myorg-myorg-controller-1   |     response = requests.get(
myorg-myorg-controller-1   |                ^^^^^^^^^^^^^
myorg-myorg-controller-1   |   File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
myorg-myorg-controller-1   |     return request("get", url, params=params, **kwargs)
myorg-myorg-controller-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
myorg-myorg-controller-1   |   File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
myorg-myorg-controller-1   |     return session.request(method=method, url=url, **kwargs)
myorg-myorg-controller-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
myorg-myorg-controller-1   |   File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
myorg-myorg-controller-1   |     resp = self.send(prep, **send_kwargs)
myorg-myorg-controller-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
myorg-myorg-controller-1   |   File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
myorg-myorg-controller-1   |     r = adapter.send(request, **kwargs)
myorg-myorg-controller-1   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
myorg-myorg-controller-1   |   File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 565, in send
myorg-myorg-controller-1   |     raise ConnectionError(e, request=request)
myorg-myorg-controller-1   | requests.exceptions.ConnectionError: HTTPConnectionPool(host='myorg-agent', port=8034): Max retries exceeded with url: /wallet/did/public (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f735241b490>: Failed to establish a new connection: [Errno 111] Connection refused'))
myorg-myorg-pipeline-1     | sleeping ...
myorg-myorg-pipeline-1     | Initializing Mara ...
myorg-myorg-pipeline-1     | >f..tp..... README.MD
myorg-myorg-pipeline-1     | >f..t...... check-newer.sh
myorg-myorg-pipeline-1     | >f..t...... ensure-pushed.sh
myorg-myorg-pipeline-1     | >f.stp..... init.mk
myorg-myorg-pipeline-1     | >f.stp..... install.mk
myorg-myorg-pipeline-1     | >f..t...... makeshell
myorg-myorg-pipeline-1     | Could not access or create database "postgresql+psycopg2://mara_db:mara_db_pwd@myorg-pipeline-db:5432/mara_db":
myorg-myorg-pipeline-1     | (psycopg2.OperationalError) connection to server at "myorg-pipeline-db" (172.30.0.3), port 5432 failed: Connection refused
myorg-myorg-pipeline-1     |    Is the server running on that host and accepting TCP/IP connections?
myorg-myorg-pipeline-1     |
myorg-myorg-pipeline-1     | (Background on this error at: http://sqlalche.me/e/13/e3q8)
myorg-myorg-pipeline-1     | .scripts/mara-app/install.mk:55: recipe for target 'migrate-mara-db' failed
myorg-myorg-pipeline-1     | make[1]: *** [migrate-mara-db] Error 255
myorg-myorg-pipeline-1     | .scripts/mara-app/install.mk:8: recipe for target 'setup-mara' failed
myorg-myorg-pipeline-1     | make: *** [setup-mara] Error 2
myorg-myorg-pipeline-1     | Starting server ...
myorg-myorg-pipeline-1     |  * Serving Flask app '/data-pipeline/app/app.py'
myorg-myorg-pipeline-1     |  * Debug mode: off
myorg-myorg-pipeline-1     | WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
myorg-myorg-pipeline-1     |  * Running on all addresses (0.0.0.0)
myorg-myorg-pipeline-1     |  * Running on http://127.0.0.1:5000
myorg-myorg-pipeline-1     |  * Running on http://172.30.0.7:5000
myorg-myorg-pipeline-1     | Press CTRL+C to quit
myorg-myorg-pipeline-1     |  * Restarting with stat
myorg-myorg-pipeline-1     | [2023-03-04 01:43:50,121] ERROR in app: Exception on / [GET]
myorg-myorg-pipeline-1     | Traceback (most recent call last):
myorg-myorg-pipeline-1     |   File "/data-pipeline/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
myorg-myorg-pipeline-1     |     response = self.full_dispatch_request()
myorg-myorg-pipeline-1     |   File "/data-pipeline/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
myorg-myorg-pipeline-1     |     rv = self.handle_user_exception(e)
myorg-myorg-pipeline-1     |   File "/data-pipeline/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in full_dispatch_request
myorg-myorg-pipeline-1     |     rv = self.preprocess_request()
myorg-myorg-pipeline-1     |   File "/data-pipeline/.venv/lib/python3.8/site-packages/flask/app.py", line 2312, in preprocess_request
myorg-myorg-pipeline-1     |     rv = self.ensure_sync(before_func)()
myorg-myorg-pipeline-1     |   File "/data-pipeline/packages/mara-acl/mara_acl/views.py", line 108, in login
myorg-myorg-pipeline-1     |     if not users.login(email):
myorg-myorg-pipeline-1     |   File "/data-pipeline/packages/mara-acl/mara_acl/users.py", line 42, in login
myorg-myorg-pipeline-1     |     cursor.execute(f"SELECT email, role FROM acl_user WHERE email = {'%s'}", (email,))
myorg-myorg-pipeline-1     | psycopg2.errors.UndefinedTable: relation "acl_user" does not exist
myorg-myorg-pipeline-1     | LINE 1: SELECT email, role FROM acl_user WHERE email = 'guest@localh...
myorg-myorg-pipeline-1     |                                 ^
myorg-myorg-pipeline-1     |
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:43:51] "GET / HTTP/1.1" 500 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:43:51] "GET /mara-app/static/bootstrap-4.0.0-alpha.6/bootstrap.min.css HTTP/1.1" 200 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:43:51] "GET /mara-app/static/tether-1.3.3/tether.min.css HTTP/1.1" 200 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:43:51] "GET /ui/static/styles.css HTTP/1.1" 200 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:43:51] "GET /mara-app/static/mara.css HTTP/1.1" 200 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:43:51] "GET /mara-app/static/font-awesome-4.7.0/css/font-awesome.min.css HTTP/1.1" 200 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:43:51] "GET /mara-app/static/tether-1.3.3/tether.min.js HTTP/1.1" 200 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:43:51] "GET /mara-app/static/jquery.floatThead.2.0.3.min.js HTTP/1.1" 200 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:43:51] "GET /ui/static/logo.png HTTP/1.1" 200 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:43:51] "GET /mara-app/static/bootstrap-4.0.0-alpha.6/bootstrap.min.js HTTP/1.1" 200 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:43:51] "GET /mara-app/static/jquery-3.1.1.min.js HTTP/1.1" 200 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:43:51] "GET /mara-app/static/mara.js HTTP/1.1" 200 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:43:51] "GET /mara-app/static/mara.jpg HTTP/1.1" 200 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:43:52] "GET /ui/static/favicon.ico HTTP/1.1" 200 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:43:52] "GET /mara-app/navigation-bar HTTP/1.1" 200 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:43:53] "GET /mara-app/static/font-awesome-4.7.0/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:43:53] "GET /ui/static/favicon.ico HTTP/1.1" 304 -
myorg-myorg-pipeline-1     | [2023-03-04 01:44:11,258] ERROR in app: Exception on /data-integration/von_data_event_processor [GET]
myorg-myorg-pipeline-1     | Traceback (most recent call last):
myorg-myorg-pipeline-1     |   File "/data-pipeline/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
myorg-myorg-pipeline-1     |     response = self.full_dispatch_request()
myorg-myorg-pipeline-1     |   File "/data-pipeline/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
myorg-myorg-pipeline-1     |     rv = self.handle_user_exception(e)
myorg-myorg-pipeline-1     |   File "/data-pipeline/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in full_dispatch_request
myorg-myorg-pipeline-1     |     rv = self.preprocess_request()
myorg-myorg-pipeline-1     |   File "/data-pipeline/.venv/lib/python3.8/site-packages/flask/app.py", line 2312, in preprocess_request
myorg-myorg-pipeline-1     |     rv = self.ensure_sync(before_func)()
myorg-myorg-pipeline-1     |   File "/data-pipeline/packages/mara-acl/mara_acl/views.py", line 108, in login
myorg-myorg-pipeline-1     |     if not users.login(email):
myorg-myorg-pipeline-1     |   File "/data-pipeline/packages/mara-acl/mara_acl/users.py", line 42, in login
myorg-myorg-pipeline-1     |     cursor.execute(f"SELECT email, role FROM acl_user WHERE email = {'%s'}", (email,))
myorg-myorg-pipeline-1     | psycopg2.errors.UndefinedTable: relation "acl_user" does not exist
myorg-myorg-pipeline-1     | LINE 1: SELECT email, role FROM acl_user WHERE email = 'guest@localh...
myorg-myorg-pipeline-1     |                                 ^
myorg-myorg-pipeline-1     |
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:44:11] "GET /data-integration/von_data_event_processor HTTP/1.1" 500 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:44:11] "GET /mara-app/static/bootstrap-4.0.0-alpha.6/bootstrap.min.css HTTP/1.1" 304 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:44:11] "GET /mara-app/static/font-awesome-4.7.0/css/font-awesome.min.css HTTP/1.1" 304 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:44:11] "GET /mara-app/static/tether-1.3.3/tether.min.css HTTP/1.1" 304 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:44:11] "GET /ui/static/styles.css HTTP/1.1" 304 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:44:11] "GET /mara-app/static/mara.css HTTP/1.1" 304 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:44:11] "GET /ui/static/logo.png HTTP/1.1" 304 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:44:11] "GET /mara-app/static/tether-1.3.3/tether.min.js HTTP/1.1" 304 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:44:11] "GET /mara-app/static/jquery-3.1.1.min.js HTTP/1.1" 304 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:44:11] "GET /mara-app/static/bootstrap-4.0.0-alpha.6/bootstrap.min.js HTTP/1.1" 304 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:44:11] "GET /mara-app/static/jquery.floatThead.2.0.3.min.js HTTP/1.1" 304 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:44:11] "GET /mara-app/static/mara.js HTTP/1.1" 304 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:44:11] "GET /mara-app/static/mara.jpg HTTP/1.1" 304 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:44:11] "GET /ui/static/favicon.ico HTTP/1.1" 304 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:44:11] "GET /mara-app/navigation-bar HTTP/1.1" 200 -
myorg-myorg-agent-1        |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
myorg-myorg-agent-1        |                                  Dload  Upload   Total   Spent    Left  Speed
myorg-myorg-agent-1        | {
myorg-myorg-agent-1        |   "did": "BCUJESvG9QcCxYRZTnkfJh",
myorg-myorg-agent-1        |   "seed": "RvqpOzMzWetWZl8alvfvtvGak3llqEMn",
myorg-myorg-agent-1        |   "verkey": "6ZNZ55gRgLLJxECTD7nu6bWxFiq4bUSJLAtpbTDPrWaK"
100   232  100   143  100    89    189    117 --:--:-- --:--:-- --:--:--   306
myorg-myorg-agent-1        | 2023-03-04 01:41:18,630 indy.libindy.native.indystrgpostgres ERROR         src/lib.rs:190 | Create storage failed: IOError("IO error during storage operation: IO error")
myorg-myorg-agent-1        | 2023-03-04 01:41:18,631 aries_cloudagent.commands.start ERROR Exception during startup:
myorg-myorg-agent-1        | Traceback (most recent call last):
myorg-myorg-agent-1        |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/indy/sdk/wallet_setup.py", line 105, in create_wallet
myorg-myorg-agent-1        |     credentials=json.dumps(self.wallet_access),
myorg-myorg-agent-1        |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/wallet.py", line 61, in create_wallet
myorg-myorg-agent-1        |     create_wallet.cb)
myorg-myorg-agent-1        | indy.error.WalletStorageError
myorg-myorg-agent-1        |
myorg-myorg-agent-1        | The above exception was the direct cause of the following exception:
myorg-myorg-agent-1        |
myorg-myorg-agent-1        | Traceback (most recent call last):
myorg-myorg-agent-1        |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 72, in init
myorg-myorg-agent-1        |     await startup
myorg-myorg-agent-1        |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 28, in start_app
myorg-myorg-agent-1        |     await conductor.setup()
myorg-myorg-agent-1        |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/core/conductor.py", line 96, in setup
myorg-myorg-agent-1        |     self.root_profile, self.setup_public_did = await wallet_config(context)
myorg-myorg-agent-1        |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/config/wallet.py", line 47, in wallet_config
myorg-myorg-agent-1        |     profile = await mgr.provision(context, profile_cfg)
myorg-myorg-agent-1        |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/indy/sdk/profile.py", line 161, in provision
myorg-myorg-agent-1        |     opened = await indy_config.create_wallet()
myorg-myorg-agent-1        |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/indy/sdk/wallet_setup.py", line 118, in create_wallet
myorg-myorg-agent-1        |     ) from x_indy
myorg-myorg-agent-1        |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/indy/sdk/wallet_setup.py", line 105, in create_wallet
myorg-myorg-agent-1        |     credentials=json.dumps(self.wallet_access),
myorg-myorg-agent-1        |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/wallet.py", line 61, in create_wallet
myorg-myorg-agent-1        |     create_wallet.cb)
myorg-myorg-agent-1        | aries_cloudagent.core.error.ProfileError: Error creating wallet 'icat_agent_wallet': Error: Wallet storage error occurred
myorg-myorg-agent-1        |   Caused by: Plugin returned error
myorg-myorg-agent-1        |
myorg-myorg-agent-1        | }
myorg-myorg-agent-1        | Shutting down
myorg-myorg-agent-1        | 2023-03-04 01:41:18,636 asyncio ERROR Task exception was never retrieved
myorg-myorg-agent-1        | future: <Task finished coro=<run_loop.<locals>.done() done, defined at /home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/start.py:77> exception=AttributeError("'NoneType' object has no attribute 'context'",)>
myorg-myorg-agent-1        | Traceback (most recent call last):
myorg-myorg-agent-1        |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 79, in done
myorg-myorg-agent-1        |     await shutdown
myorg-myorg-agent-1        |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 35, in shutdown_app
myorg-myorg-agent-1        |     await conductor.stop()
myorg-myorg-agent-1        |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/core/conductor.py", line 361, in stop
myorg-myorg-agent-1        |     multitenant_mgr = self.context.inject_or(MultitenantManager)
myorg-myorg-agent-1        |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/core/conductor.py", line 85, in context
myorg-myorg-agent-1        |     return self.root_profile.context
myorg-myorg-agent-1        | AttributeError: 'NoneType' object has no attribute 'context'
myorg-myorg-pipeline-db-1  | 2023-03-04 01:50:35.285 UTC [126] ERROR:  relation "acl_user" does not exist at character 25
myorg-myorg-pipeline-db-1  | 2023-03-04 01:50:35.285 UTC [126] STATEMENT:  SELECT email, role FROM acl_user WHERE email = 'guest@localhost'
myorg-myorg-pipeline-1     | [2023-03-04 01:50:35,287] ERROR in app: Exception on / [GET]
myorg-myorg-pipeline-1     | Traceback (most recent call last):
myorg-myorg-pipeline-1     |   File "/data-pipeline/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
myorg-myorg-pipeline-1     |     response = self.full_dispatch_request()
myorg-myorg-pipeline-1     |   File "/data-pipeline/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
myorg-myorg-pipeline-1     |     rv = self.handle_user_exception(e)
myorg-myorg-pipeline-1     |   File "/data-pipeline/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in full_dispatch_request
myorg-myorg-pipeline-1     |     rv = self.preprocess_request()
myorg-myorg-pipeline-1     |   File "/data-pipeline/.venv/lib/python3.8/site-packages/flask/app.py", line 2312, in preprocess_request
myorg-myorg-pipeline-1     |     rv = self.ensure_sync(before_func)()
myorg-myorg-pipeline-1     |   File "/data-pipeline/packages/mara-acl/mara_acl/views.py", line 108, in login
myorg-myorg-pipeline-1     |     if not users.login(email):
myorg-myorg-pipeline-1     |   File "/data-pipeline/packages/mara-acl/mara_acl/users.py", line 42, in login
myorg-myorg-pipeline-1     |     cursor.execute(f"SELECT email, role FROM acl_user WHERE email = {'%s'}", (email,))
myorg-myorg-pipeline-1     | psycopg2.errors.UndefinedTable: relation "acl_user" does not exist
myorg-myorg-pipeline-1     | LINE 1: SELECT email, role FROM acl_user WHERE email = 'guest@localh...
myorg-myorg-pipeline-1     |                                 ^
myorg-myorg-pipeline-1     |
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:50:35] "GET / HTTP/1.1" 500 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:50:35] "GET /mara-app/static/bootstrap-4.0.0-alpha.6/bootstrap.min.css HTTP/1.1" 200 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:50:35] "GET /ui/static/styles.css HTTP/1.1" 200 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:50:35] "GET /mara-app/static/mara.css HTTP/1.1" 200 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:50:35] "GET /mara-app/static/tether-1.3.3/tether.min.css HTTP/1.1" 200 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:50:35] "GET /mara-app/static/font-awesome-4.7.0/css/font-awesome.min.css HTTP/1.1" 200 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:50:36] "GET /mara-app/static/tether-1.3.3/tether.min.js HTTP/1.1" 200 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:50:36] "GET /mara-app/static/bootstrap-4.0.0-alpha.6/bootstrap.min.js HTTP/1.1" 200 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:50:36] "GET /mara-app/static/mara.js HTTP/1.1" 200 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:50:36] "GET /mara-app/static/jquery-3.1.1.min.js HTTP/1.1" 200 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:50:36] "GET /mara-app/static/jquery.floatThead.2.0.3.min.js HTTP/1.1" 200 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:50:36] "GET /ui/static/logo.png HTTP/1.1" 200 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:50:36] "GET /mara-app/static/mara.jpg HTTP/1.1" 200 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:50:38] "GET /mara-app/navigation-bar HTTP/1.1" 200 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:50:38] "GET /ui/static/favicon.ico HTTP/1.1" 200 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:50:38] "GET /mara-app/static/font-awesome-4.7.0/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 -
myorg-myorg-pipeline-1     | 172.30.0.1 - - [04/Mar/2023 01:50:38] "GET /ui/static/favicon.ico HTTP/1.1" 304 -

```

**Comment by ianco** [comment]
This looks like a timing issue to me.  The containers are trying to access the databases but the database containers haven't started up yet.

Try running `./manage stop` and then `./manage start` - this will recycle the containers without deleting any of the previously initialized volumes.  For the second `./manage start` the databases start up faster because they don't have to run the initialization steps, and this sometimes solves these kinds of timing issues.

**Comment by ianco** [comment]
A useful tip is to run `./manage start --logs` and then you can see the containers startup in realtime, and then you can see exactly if there is a timing issue (i.e. the database initalization happens after the application error)
